/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd;

/**
 *
 * @author Adnan & Arman
 */
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
public class drugDB extends javax.swing.JFrame {

    /**
     * Creates new form drugDB
     */
    

    public drugDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        about = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        moreinfo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        uses = new javax.swing.JTextArea();
        button = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_MouseClicked(evt);
            }
        });
        getContentPane().add(exit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 0, 35, 35));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setColumns(20);
        search.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setRows(1);
        jScrollPane1.setViewportView(search);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 390, 40));

        about.setBackground(new java.awt.Color(51, 51, 51));
        about.setColumns(20);
        about.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setRows(5);
        jScrollPane2.setViewportView(about);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 430, 180));

        moreinfo.setBackground(new java.awt.Color(51, 51, 51));
        moreinfo.setColumns(20);
        moreinfo.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        moreinfo.setForeground(new java.awt.Color(255, 255, 255));
        moreinfo.setRows(5);
        jScrollPane3.setViewportView(moreinfo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 116, 390, 460));

        uses.setBackground(new java.awt.Color(51, 51, 51));
        uses.setColumns(20);
        uses.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        uses.setForeground(new java.awt.Color(255, 255, 255));
        uses.setRows(5);
        jScrollPane4.setViewportView(uses);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 396, 420, 180));

        button.setText("jLabel1");
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, 40));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/drugData.png"))); // NOI18N
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_MouseClicked
        this.dispose();
    }//GEN-LAST:event_exit_MouseClicked

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked



String url="jdbc:mysql://127.0.0.1/drugdictionary";

String username="root";
String password="";
String query="SELECT * FROM drugdictionary WHERE name='"+search.getText()+"'";
try{
Class.forName("com.mysql.jdbc.Driver");
Connection connection=(Connection) DriverManager.getConnection(url,username,password);
Statement statement=connection.createStatement();
ResultSet result;
result=statement.executeQuery(query);
result.next();
String a = result.getString("about");
about.setText(a);
String u = result.getString("uses");
uses.setText(u);
String m = result.getString("moreinfo");
moreinfo.setText(m);

connection.close();
statement.close();

}catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}









        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drugDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drugDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drugDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drugDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drugDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea about;
    private javax.swing.JLabel button;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel exit_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea moreinfo;
    private javax.swing.JTextArea search;
    private javax.swing.JTextArea uses;
    // End of variables declaration//GEN-END:variables
}
