/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd;

/**
 *
 * @author Adnan & Arman
 */
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
public class genDictionary extends javax.swing.JFrame {

    /**
     * Creates new form diseaseDB
     */
    public genDictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        rslt = new javax.swing.JTextArea();
        button = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_MouseClicked(evt);
            }
        });
        getContentPane().add(exit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 0, 35, 35));

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setColumns(20);
        search.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setRows(1);
        jScrollPane1.setViewportView(search);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 40));

        rslt.setBackground(new java.awt.Color(51, 51, 51));
        rslt.setColumns(20);
        rslt.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        rslt.setForeground(new java.awt.Color(255, 255, 255));
        rslt.setRows(5);
        jScrollPane3.setViewportView(rslt);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 430, 180));

        button.setText("jLabel1");
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 40));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/diseaseData.png"))); // NOI18N
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        jTextArea2.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(1);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_MouseClicked
        this.dispose();
    }//GEN-LAST:event_exit_MouseClicked

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked

String url="jdbc:mysql://127.0.0.1/gendictionary";

String username="root";
String password="";
String query="SELECT * FROM gendictionary WHERE input='"+search.getText()+"'";
try{
Class.forName("com.mysql.jdbc.Driver");
Connection connection=(Connection) DriverManager.getConnection(url,username,password);
Statement statement=connection.createStatement();
ResultSet result;
result=statement.executeQuery(query);
result.next();
String s = result.getString("meaning");
rslt.setText(s);
connection.close();
statement.close();

}catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}

        
    }//GEN-LAST:event_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(genDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(genDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(genDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(genDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new genDictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel exit_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea rslt;
    private javax.swing.JTextArea search;
    // End of variables declaration//GEN-END:variables
}
