/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd;

/**
 *
 * @author Adnan & Arman
 */

public class timePnl extends javax.swing.JFrame {

    /**
     * Creates new form timePnl
     */
    
    
    String timeSet = "";

    public timePnl(int x,int y) {
        initComponents();
        this.setLocation(x,y);
    }
    
    int cnt=0;
    public timePnl() {
        initComponents();
        
        this.setLocation(100,200);
        //this.setLocation(t.retX(), t.retY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        twelve_ = new javax.swing.JLabel();
        one_ = new javax.swing.JLabel();
        two_ = new javax.swing.JLabel();
        three_ = new javax.swing.JLabel();
        four_ = new javax.swing.JLabel();
        five_ = new javax.swing.JLabel();
        six_ = new javax.swing.JLabel();
        seven_ = new javax.swing.JLabel();
        eight_ = new javax.swing.JLabel();
        nine_ = new javax.swing.JLabel();
        ten_ = new javax.swing.JLabel();
        eleven_ = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        twelve_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twelve_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twelve_MouseClicked(evt);
            }
        });
        getContentPane().add(twelve_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 100, 20));

        one_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        one_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                one_MouseClicked(evt);
            }
        });
        getContentPane().add(one_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 100, 20));

        two_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                two_MouseClicked(evt);
            }
        });
        getContentPane().add(two_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 100, 20));

        three_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        three_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                three_MouseClicked(evt);
            }
        });
        getContentPane().add(three_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, 20));

        four_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        four_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                four_MouseClicked(evt);
            }
        });
        getContentPane().add(four_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 100, 20));

        five_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        five_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                five_MouseClicked(evt);
            }
        });
        getContentPane().add(five_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 100, 20));

        six_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        six_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                six_MouseClicked(evt);
            }
        });
        getContentPane().add(six_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, 100, 20));

        seven_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seven_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seven_MouseClicked(evt);
            }
        });
        getContentPane().add(seven_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 159, 100, 20));

        eight_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eight_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eight_MouseClicked(evt);
            }
        });
        getContentPane().add(eight_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, 100, 20));

        nine_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nine_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nine_MouseClicked(evt);
            }
        });
        getContentPane().add(nine_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 203, 100, 20));

        ten_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ten_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ten_MouseClicked(evt);
            }
        });
        getContentPane().add(ten_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 100, 20));

        eleven_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eleven_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleven_MouseClicked(evt);
            }
        });
        getContentPane().add(eleven_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 247, 100, 20));

        drag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/clockMouseMove.png"))); // NOI18N
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twelve_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twelve_MouseClicked
        timeSet = "12:0:0";
        this.dispose();
    }//GEN-LAST:event_twelve_MouseClicked

    private void one_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_MouseClicked
        timeSet = "1:0:0";
        this.dispose();
    }//GEN-LAST:event_one_MouseClicked

    private void two_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_MouseClicked
        timeSet = "2:0:0";
        this.dispose();
    }//GEN-LAST:event_two_MouseClicked

    private void three_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_three_MouseClicked
        timeSet = "3:0:0";
        this.dispose();
    }//GEN-LAST:event_three_MouseClicked

    private void four_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_four_MouseClicked
        timeSet = "4:0:0";
        this.dispose();
    }//GEN-LAST:event_four_MouseClicked

    private void five_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_five_MouseClicked
        timeSet = "5:0:0";
        this.dispose();
    }//GEN-LAST:event_five_MouseClicked

    private void six_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_six_MouseClicked
        timeSet = "6:0:0";
        this.dispose();
    }//GEN-LAST:event_six_MouseClicked

    private void seven_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seven_MouseClicked
        timeSet = "7:0:0";
        this.dispose();
    }//GEN-LAST:event_seven_MouseClicked

    private void eight_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eight_MouseClicked
        timeSet = "8:0:0";
        this.dispose();
    }//GEN-LAST:event_eight_MouseClicked

    private void nine_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nine_MouseClicked
        timeSet = "9:0:0";
        this.dispose();
    }//GEN-LAST:event_nine_MouseClicked

    private void ten_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ten_MouseClicked
        timeSet = "10:0:0";
        this.dispose();
    }//GEN-LAST:event_ten_MouseClicked

    private void eleven_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleven_MouseClicked
        timeSet = "11:0:0";
        this.dispose();
    }//GEN-LAST:event_eleven_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timePnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timePnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timePnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timePnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timePnl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drag;
    private javax.swing.JLabel eight_;
    private javax.swing.JLabel eleven_;
    private javax.swing.JLabel five_;
    private javax.swing.JLabel four_;
    private javax.swing.JLabel nine_;
    private javax.swing.JLabel one_;
    private javax.swing.JLabel seven_;
    private javax.swing.JLabel six_;
    private javax.swing.JLabel ten_;
    private javax.swing.JLabel three_;
    private javax.swing.JLabel twelve_;
    private javax.swing.JLabel two_;
    // End of variables declaration//GEN-END:variables
}
