/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd;


/**
 *
 * @author Adnan & Arman
 */
public class todoPanel extends javax.swing.JFrame {

    /**
     * Creates new form todoPanel
     */
    
    int mouseX;
    int mouseY;
    int pnlX;//.getLocationOnScreen().x;
    int pnlY;//.getLocationOnScreen().y;
    timePnl tp  ;
    int X,Y;
    
    public todoPanel(int x,int y) {
        initComponents();
        X=x;
        Y=y;
        this.setLocation(X,Y+100);
        name_.setBackground(new java.awt.Color(255,255,255,0));
        ampm.setText("AM");
        
    }
    
    
    
    public todoPanel() {
        initComponents();
        this.setLocation(400,200);
        name_.setBackground(new java.awt.Color(255,255,255,0));
        ampm.setText("AM");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_ = new javax.swing.JLabel();
        recall_ = new javax.swing.JLabel();
        color_ = new javax.swing.JLabel();
        name_ = new javax.swing.JTextField();
        txt_ = new javax.swing.JScrollPane();
        tt_ = new javax.swing.JTextArea();
        ok_ = new javax.swing.JLabel();
        time_ = new javax.swing.JLabel();
        timeEx = new javax.swing.JLabel();
        ampm = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_MouseClicked(evt);
            }
        });
        getContentPane().add(exit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 0, 28, 28));

        recall_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recall_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recall_MouseClicked(evt);
            }
        });
        getContentPane().add(recall_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 28, 28));

        color_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(color_, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 0, 28, 28));

        name_.setForeground(new java.awt.Color(255, 255, 255));
        name_.setBorder(null);
        name_.setOpaque(false);
        getContentPane().add(name_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 293, 30));

        txt_.setBackground(new java.awt.Color(30, 30, 30));
        txt_.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        txt_.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tt_.setBackground(new java.awt.Color(60, 60, 60));
        tt_.setColumns(1);
        tt_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_.setLineWrap(true);
        tt_.setRows(5);
        tt_.setWrapStyleWord(true);
        tt_.setAutoscrolls(false);
        tt_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tt_.setOpaque(false);
        txt_.setViewportView(tt_);

        getContentPane().add(txt_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 293, 133));

        ok_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ok_MousePressed(evt);
            }
        });
        getContentPane().add(ok_, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 276, 30, 20));

        time_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        time_.setForeground(new java.awt.Color(255, 255, 255));
        time_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_.setText("00.00");
        time_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        time_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                time_MouseMoved(evt);
            }
        });
        getContentPane().add(time_, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 272, 80, 28));

        timeEx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeExMouseClicked(evt);
            }
        });
        getContentPane().add(timeEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 276, 20, 20));

        ampm.setForeground(new java.awt.Color(255, 255, 255));
        ampm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ampmMouseClicked(evt);
            }
        });
        getContentPane().add(ampm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 277, 20, 20));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/todoPanel.png"))); // NOI18N
        drag_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drag_MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drag_MouseMoved(evt);
            }
        });
        drag_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drag_MousePressed(evt);
            }
        });
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 313, 313));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_MouseClicked
            this.dispose();
    }//GEN-LAST:event_exit_MouseClicked

    private void recall_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recall_MouseClicked
        todoPanel tdp = new todoPanel();
        tdp.setVisible(true);
    }//GEN-LAST:event_recall_MouseClicked

    private void drag_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
        
    }//GEN-LAST:event_drag_MouseDragged

    private void drag_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_drag_MousePressed
        //String str[] = new String[5];
        //String str2[] = new String[5];
    String str = "";
    String str2 = "";
        String time = "";
        int i=0;
    private void ok_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_MousePressed
        //str[i] = name_.getText();
        //str2[i] = tt_.getText();
        //time = ;
        /*str = str.concat(name_.getText());
        
        
        toDo t = new toDo();
        t.showLog(i,str);
        t.setVisible(true);
        i++;
        this.dispose();*/
        
        this.dispose();
        toDo td = new toDo(X,Y);
        td.setVisible(true);
        
    }//GEN-LAST:event_ok_MousePressed

    private void drag_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseMoved
       // tp.setVisible(false);
        flag =0;
    }//GEN-LAST:event_drag_MouseMoved
    int flag=0; 
    int cnt=0;
   // timePnl tp  = new timePnl(pnlX,pnlY) ;
    private void time_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_time_MouseMoved
         
        
        
        
        /*
        
        pnlX = evt.getXOnScreen();
         pnlY = evt.getYOnScreen();
        flag = 1;
        if(flag ==1 && cnt < 1){
        tp= new timePnl(this.retX(),this.retY());
        tp.setVisible(true);
        cnt++;
        }
        if(!tp.isActive()){
            cnt  = 1;
        }
        
        else tp.setVisible(false);
        System.out.println(pnlY);
        System.out.println(pnlX);
        */
    }//GEN-LAST:event_time_MouseMoved

    private void timeExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeExMouseClicked
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        timePnl tt = new timePnl(xx-100,yy);
        tt.setVisible(true);
    }//GEN-LAST:event_timeExMouseClicked
    
    String ampmset="";
    private void ampmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ampmMouseClicked
        
        if(ampm.getText().equals("AM")){
        ampmset = "PM";ampm.setText(ampmset);
        }
        else {
        ampmset = "AM";
        ampm.setText(ampmset);
        }
            
            
    }//GEN-LAST:event_ampmMouseClicked

    
    public int retX(){
        System.out.println(pnlX);
    return pnlX;
    }
    public int retY(){
        System.out.println(pnlY);
    return pnlY;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(todoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(todoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(todoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(todoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new todoPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ampm;
    private javax.swing.JLabel color_;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel exit_;
    private javax.swing.JTextField name_;
    private javax.swing.JLabel ok_;
    private javax.swing.JLabel recall_;
    private javax.swing.JLabel timeEx;
    private javax.swing.JLabel time_;
    private javax.swing.JTextArea tt_;
    private javax.swing.JScrollPane txt_;
    // End of variables declaration//GEN-END:variables
}
