/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;
import java.io.*;
import java.util.Scanner;
import java.lang.*;
import javax.swing.*;

/**
 *
 * @author Adnan & Arman
 */
public class toDo extends javax.swing.JFrame {

    
    public String time;
    public String msg;
    /**
     * Creates new form toDo
     */
    public toDo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_ = new javax.swing.JLabel();
        remind = new javax.swing.JLabel();
        remind_msg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        remindMsg = new javax.swing.JTextArea();
        Time = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        remindTim = new javax.swing.JTextArea();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_MouseClicked(evt);
            }
        });
        getContentPane().add(exit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 15, 30, 30));

        remind.setText("Remind about: ");
        getContentPane().add(remind, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 20));

        remind_msg.setText("Set Reminder");
        remind_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remind_msgActionPerformed(evt);
            }
        });
        getContentPane().add(remind_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, 40));

        remindMsg.setColumns(100);
        remindMsg.setRows(1);
        remindMsg.setLineWrap (true);
        remindMsg.setWrapStyleWord (false);
        jScrollPane1.setViewportView(remindMsg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 50));

        Time.setText("Time:");
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 20));

        remindTim.setColumns(100);
        remindTim.setRows(1);
        remindTim.setLineWrap (true);
        remindTim.setWrapStyleWord (false);
        jScrollPane2.setViewportView(remindTim);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 40));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/todoList.png"))); // NOI18N
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 313, 483));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_MouseClicked
        this.dispose();
    }//GEN-LAST:event_exit_MouseClicked

    private void remind_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remind_msgActionPerformed
       time=remindTim.getText();
       msg=remindMsg.getText();
     
     Windows_Notification wn= new Windows_Notification(msg,time);
     
    try{ 
        
       
     wn.Notification();
     
     
    }catch(Exception e){
        e.printStackTrace();
    }
    
    
     //String joined=msg+time;   
       
        /*try
        {   String path="C:\\Users\\User\\Documents\\NetBeansProjects\\pShow\\toDoList.txt";
            File f= new File(path);
            f.createNewFile();
            
            BufferedWriter writer = new BufferedWriter(new FileWriter(f));
            writer.write(joined);
     
            writer.close();
        }catch(Exception e)
        {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_remind_msgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toDo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Time;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel exit_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel remind;
    private javax.swing.JTextArea remindMsg;
    private javax.swing.JTextArea remindTim;
    private javax.swing.JButton remind_msg;
    // End of variables declaration//GEN-END:variables



}
