/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package typemaster_mini;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Adnan & Arman
 */
public class typeMaster_mini extends javax.swing.JFrame {

    /**
     * Creates new form typeMasterMini
     */
    
    
    // screen height width
    int wid = (Toolkit.getDefaultToolkit().getScreenSize().width)/2-400;
    int hit = (Toolkit.getDefaultToolkit().getScreenSize().height)/2-300;
    
    // string shift and capslock state declare
    String str = "";
    int shiftFlag = 0;
    boolean capsLockFlag = false;
    
    
    public typeMaster_mini() {
        initComponents();
        this.setLocation(wid, hit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_ = new javax.swing.JLabel();
        O_ = new javax.swing.JLabel();
        P_ = new javax.swing.JLabel();
        brac1_ = new javax.swing.JLabel();
        L_ = new javax.swing.JLabel();
        K_ = new javax.swing.JLabel();
        J_ = new javax.swing.JLabel();
        H_ = new javax.swing.JLabel();
        G_ = new javax.swing.JLabel();
        F_ = new javax.swing.JLabel();
        D_ = new javax.swing.JLabel();
        S_ = new javax.swing.JLabel();
        A_ = new javax.swing.JLabel();
        Z_ = new javax.swing.JLabel();
        X_ = new javax.swing.JLabel();
        C_ = new javax.swing.JLabel();
        V_ = new javax.swing.JLabel();
        B_ = new javax.swing.JLabel();
        N_ = new javax.swing.JLabel();
        M_ = new javax.swing.JLabel();
        space_ = new javax.swing.JLabel();
        Q_ = new javax.swing.JLabel();
        W_ = new javax.swing.JLabel();
        E_ = new javax.swing.JLabel();
        R_ = new javax.swing.JLabel();
        T_ = new javax.swing.JLabel();
        Y_ = new javax.swing.JLabel();
        U_ = new javax.swing.JLabel();
        I_ = new javax.swing.JLabel();
        pathetic_ = new javax.swing.JScrollPane();
        writeUser_ = new javax.swing.JTextArea();
        pathetic2_ = new javax.swing.JScrollPane();
        fileWrite_ = new javax.swing.JTextArea();
        enter1_ = new javax.swing.JLabel();
        enter2_ = new javax.swing.JLabel();
        submit_ = new javax.swing.JLabel();
        about_ = new javax.swing.JLabel();
        rightShift_ = new javax.swing.JLabel();
        backSlash_ = new javax.swing.JLabel();
        tab_ = new javax.swing.JLabel();
        capsLock_ = new javax.swing.JLabel();
        leftShift_ = new javax.swing.JLabel();
        symbl_ = new javax.swing.JLabel();
        one_ = new javax.swing.JLabel();
        two_ = new javax.swing.JLabel();
        three_ = new javax.swing.JLabel();
        four_ = new javax.swing.JLabel();
        five_ = new javax.swing.JLabel();
        six_ = new javax.swing.JLabel();
        seven_ = new javax.swing.JLabel();
        eight_ = new javax.swing.JLabel();
        nine_ = new javax.swing.JLabel();
        zero_ = new javax.swing.JLabel();
        dash_ = new javax.swing.JLabel();
        equal_ = new javax.swing.JLabel();
        backspace_ = new javax.swing.JLabel();
        brac2_ = new javax.swing.JLabel();
        udd_ = new javax.swing.JLabel();
        comma_ = new javax.swing.JLabel();
        fullstop_ = new javax.swing.JLabel();
        slash_ = new javax.swing.JLabel();
        semi_ = new javax.swing.JLabel();
        drgen_ = new javax.swing.JLabel();
        enterImage_ = new javax.swing.JLabel();
        showText_ = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_MouseClicked(evt);
            }
        });
        getContentPane().add(exit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 60, 40));

        O_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        O_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                O_MouseMoved(evt);
            }
        });
        O_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                O_MouseClicked(evt);
            }
        });
        getContentPane().add(O_, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 380, 44, 44));

        P_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        P_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                P_MouseMoved(evt);
            }
        });
        P_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_MouseClicked(evt);
            }
        });
        getContentPane().add(P_, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 380, 44, 44));

        brac1_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brac1_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                brac1_MouseMoved(evt);
            }
        });
        brac1_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brac1_MouseClicked(evt);
            }
        });
        getContentPane().add(brac1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 380, 44, 44));

        L_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                L_MouseMoved(evt);
            }
        });
        L_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_MouseClicked(evt);
            }
        });
        getContentPane().add(L_, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 432, 44, 44));

        K_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        K_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                K_MouseMoved(evt);
            }
        });
        K_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                K_MouseClicked(evt);
            }
        });
        getContentPane().add(K_, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 432, 44, 44));

        J_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        J_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                J_MouseMoved(evt);
            }
        });
        J_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_MouseClicked(evt);
            }
        });
        getContentPane().add(J_, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 432, 44, 44));

        H_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        H_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                H_MouseMoved(evt);
            }
        });
        H_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H_MouseClicked(evt);
            }
        });
        getContentPane().add(H_, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 432, 44, 44));

        G_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                G_MouseMoved(evt);
            }
        });
        G_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G_MouseClicked(evt);
            }
        });
        getContentPane().add(G_, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 432, 44, 44));

        F_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        F_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                F_MouseMoved(evt);
            }
        });
        F_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F_MouseClicked(evt);
            }
        });
        getContentPane().add(F_, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 432, 44, 44));

        D_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                D_MouseMoved(evt);
            }
        });
        D_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_MouseClicked(evt);
            }
        });
        getContentPane().add(D_, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 432, 44, 44));

        S_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                S_MouseMoved(evt);
            }
        });
        S_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MouseClicked(evt);
            }
        });
        getContentPane().add(S_, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 432, 44, 44));

        A_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                A_MouseMoved(evt);
            }
        });
        A_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_MouseClicked(evt);
            }
        });
        getContentPane().add(A_, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 432, 44, 44));

        Z_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Z_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Z_MouseMoved(evt);
            }
        });
        Z_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Z_MouseClicked(evt);
            }
        });
        getContentPane().add(Z_, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 484, 44, 44));

        X_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                X_MouseMoved(evt);
            }
        });
        X_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X_MouseClicked(evt);
            }
        });
        getContentPane().add(X_, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 484, 44, 44));

        C_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        C_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                C_MouseMoved(evt);
            }
        });
        C_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_MouseClicked(evt);
            }
        });
        getContentPane().add(C_, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 484, 44, 44));

        V_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        V_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                V_MouseMoved(evt);
            }
        });
        V_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V_MouseClicked(evt);
            }
        });
        getContentPane().add(V_, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 484, 44, 44));

        B_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                B_MouseMoved(evt);
            }
        });
        B_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_MouseClicked(evt);
            }
        });
        getContentPane().add(B_, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 484, 44, 44));

        N_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        N_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                N_MouseMoved(evt);
            }
        });
        N_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_MouseClicked(evt);
            }
        });
        getContentPane().add(N_, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 484, 44, 44));

        M_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                M_MouseMoved(evt);
            }
        });
        M_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MouseClicked(evt);
            }
        });
        getContentPane().add(M_, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 484, 44, 44));

        space_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        space_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                space_MouseMoved(evt);
            }
        });
        space_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                space_MouseClicked(evt);
            }
        });
        getContentPane().add(space_, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 536, 262, 44));

        Q_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Q_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Q_MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Q_MouseMoved(evt);
            }
        });
        Q_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q_MouseClicked(evt);
            }
        });
        getContentPane().add(Q_, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 380, 44, 44));

        W_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        W_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                W_MouseMoved(evt);
            }
        });
        W_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W_MouseClicked(evt);
            }
        });
        getContentPane().add(W_, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 380, 44, 44));

        E_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        E_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                E_MouseMoved(evt);
            }
        });
        E_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E_MouseClicked(evt);
            }
        });
        getContentPane().add(E_, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 380, 44, 44));

        R_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                R_MouseMoved(evt);
            }
        });
        R_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R_MouseClicked(evt);
            }
        });
        getContentPane().add(R_, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 380, 44, 44));

        T_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        T_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                T_MouseMoved(evt);
            }
        });
        T_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_MouseClicked(evt);
            }
        });
        getContentPane().add(T_, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 380, 44, 44));

        Y_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Y_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Y_MouseMoved(evt);
            }
        });
        Y_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Y_MouseClicked(evt);
            }
        });
        getContentPane().add(Y_, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 380, 44, 44));

        U_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        U_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                U_MouseMoved(evt);
            }
        });
        U_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_MouseClicked(evt);
            }
        });
        getContentPane().add(U_, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 380, 44, 44));

        I_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        I_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                I_MouseMoved(evt);
            }
        });
        I_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                I_MouseClicked(evt);
            }
        });
        getContentPane().add(I_, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 380, 44, 44));

        pathetic_.setBorder(null);

        writeUser_.setEditable(false);
        writeUser_.setBackground(new java.awt.Color(37, 37, 37));
        writeUser_.setColumns(20);
        writeUser_.setForeground(new java.awt.Color(255, 255, 255));
        writeUser_.setRows(4);
        writeUser_.setBorder(null);
        writeUser_.setOpaque(false);
        pathetic_.setViewportView(writeUser_);

        getContentPane().add(pathetic_, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 205, 740, 85));

        pathetic2_.setBorder(null);
        pathetic2_.setOpaque(false);

        fileWrite_.setEditable(false);
        fileWrite_.setBackground(new java.awt.Color(38, 20, 20));
        fileWrite_.setColumns(20);
        fileWrite_.setForeground(new java.awt.Color(255, 255, 255));
        fileWrite_.setRows(5);
        fileWrite_.setOpaque(false);
        pathetic2_.setViewportView(fileWrite_);

        getContentPane().add(pathetic2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 32, 650, 137));

        enter1_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter1_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enter1_MouseMoved(evt);
            }
        });
        enter1_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter1_MouseClicked(evt);
            }
        });
        getContentPane().add(enter1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 432, 85, 44));

        enter2_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter2_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enter2_MouseMoved(evt);
            }
        });
        enter2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter2_MouseClicked(evt);
            }
        });
        getContentPane().add(enter2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 44, 56));

        submit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                submit_MouseMoved(evt);
            }
        });
        submit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_MouseClicked(evt);
            }
        });
        getContentPane().add(submit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 536, 152, 44));

        about_.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        about_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                about_MouseMoved(evt);
            }
        });
        about_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_MouseClicked(evt);
            }
        });
        getContentPane().add(about_, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 536, 44, 44));

        rightShift_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightShift_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rightShift_MouseMoved(evt);
            }
        });
        rightShift_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightShift_MouseClicked(evt);
            }
        });
        getContentPane().add(rightShift_, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 484, 111, 44));

        backSlash_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backSlash_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backSlash_MouseMoved(evt);
            }
        });
        backSlash_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backSlash_MouseClicked(evt);
            }
        });
        getContentPane().add(backSlash_, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 536, 44, 44));

        tab_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tab_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tab_MouseMoved(evt);
            }
        });
        tab_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_MouseClicked(evt);
            }
        });
        getContentPane().add(tab_, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 380, 72, 44));

        capsLock_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        capsLock_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                capsLock_MouseMoved(evt);
            }
        });
        capsLock_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capsLock_MouseClicked(evt);
            }
        });
        getContentPane().add(capsLock_, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 432, 85, 44));

        leftShift_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftShift_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                leftShift_MouseMoved(evt);
            }
        });
        leftShift_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftShift_MouseClicked(evt);
            }
        });
        getContentPane().add(leftShift_, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 484, 111, 44));

        symbl_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        symbl_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                symbl_MouseMoved(evt);
            }
        });
        symbl_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                symbl_MouseClicked(evt);
            }
        });
        getContentPane().add(symbl_, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 328, 44, 44));

        one_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        one_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                one_MouseMoved(evt);
            }
        });
        one_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                one_MouseClicked(evt);
            }
        });
        getContentPane().add(one_, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 328, 44, 44));

        two_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                two_MouseMoved(evt);
            }
        });
        two_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                two_MouseClicked(evt);
            }
        });
        getContentPane().add(two_, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 328, 44, 44));

        three_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        three_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                three_MouseMoved(evt);
            }
        });
        three_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                three_MouseClicked(evt);
            }
        });
        getContentPane().add(three_, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 328, 44, 44));

        four_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        four_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                four_MouseMoved(evt);
            }
        });
        four_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                four_MouseClicked(evt);
            }
        });
        getContentPane().add(four_, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 328, 44, 44));

        five_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        five_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                five_MouseMoved(evt);
            }
        });
        five_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                five_MouseClicked(evt);
            }
        });
        getContentPane().add(five_, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 328, 44, 44));

        six_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        six_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                six_MouseMoved(evt);
            }
        });
        six_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                six_MouseClicked(evt);
            }
        });
        getContentPane().add(six_, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 328, 44, 44));

        seven_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seven_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                seven_MouseMoved(evt);
            }
        });
        seven_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seven_MouseClicked(evt);
            }
        });
        getContentPane().add(seven_, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 328, 44, 44));

        eight_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eight_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                eight_MouseMoved(evt);
            }
        });
        eight_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eight_MouseClicked(evt);
            }
        });
        getContentPane().add(eight_, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 328, 44, 44));

        nine_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nine_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nine_MouseMoved(evt);
            }
        });
        nine_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nine_MouseClicked(evt);
            }
        });
        getContentPane().add(nine_, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 328, 44, 44));

        zero_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zero_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                zero_MouseMoved(evt);
            }
        });
        zero_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zero_MouseClicked(evt);
            }
        });
        getContentPane().add(zero_, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 328, 44, 44));

        dash_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dash_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dash_MouseMoved(evt);
            }
        });
        dash_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash_MouseClicked(evt);
            }
        });
        getContentPane().add(dash_, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 328, 44, 44));

        equal_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equal_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                equal_MouseMoved(evt);
            }
        });
        equal_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equal_MouseClicked(evt);
            }
        });
        getContentPane().add(equal_, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 328, 44, 44));

        backspace_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backspace_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backspace_MouseMoved(evt);
            }
        });
        backspace_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backspace_MouseClicked(evt);
            }
        });
        getContentPane().add(backspace_, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 328, 71, 44));

        brac2_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brac2_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                brac2_MouseMoved(evt);
            }
        });
        brac2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brac2_MouseClicked(evt);
            }
        });
        getContentPane().add(brac2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 380, 44, 44));

        udd_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        udd_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                udd_MouseMoved(evt);
            }
        });
        udd_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                udd_MouseClicked(evt);
            }
        });
        getContentPane().add(udd_, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 432, 44, 44));

        comma_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comma_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                comma_MouseMoved(evt);
            }
        });
        comma_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comma_MouseClicked(evt);
            }
        });
        getContentPane().add(comma_, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 484, 44, 44));

        fullstop_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fullstop_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fullstop_MouseMoved(evt);
            }
        });
        fullstop_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullstop_MouseClicked(evt);
            }
        });
        getContentPane().add(fullstop_, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 484, 44, 44));

        slash_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slash_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                slash_MouseMoved(evt);
            }
        });
        slash_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slash_MouseClicked(evt);
            }
        });
        getContentPane().add(slash_, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 484, 44, 44));

        semi_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semi_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                semi_MouseMoved(evt);
            }
        });
        semi_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semi_MouseClicked(evt);
            }
        });
        getContentPane().add(semi_, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 432, 44, 44));

        drgen_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drgen_MouseMoved(evt);
            }
        });
        getContentPane().add(drgen_, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 380, 40, 51));

        enterImage_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enterImage_MouseMoved(evt);
            }
        });
        getContentPane().add(enterImage_, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 380, 85, 95));

        showText_.setToolTipText("show file");
        showText_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showText_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showText_MouseClicked(evt);
            }
        });
        getContentPane().add(showText_, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 132, 32, 32));

        drag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/typemaster_mini/typeMasterFinal.png"))); // NOI18N
        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dragMouseMoved(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exit_MouseClicked

    private void Q_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("Q");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("q");
        writeUser_.setText(str);
    }//GEN-LAST:event_Q_MouseClicked

    private void leftShift_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftShift_MouseClicked
        // TODO add your handling code here:
        shiftFlag  = 1;
    }//GEN-LAST:event_leftShift_MouseClicked

    private void capsLock_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capsLock_MouseClicked
        // TODO add your handling code here:
        capsLockFlag  = !capsLockFlag;
    }//GEN-LAST:event_capsLock_MouseClicked

    private void tab_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_MouseClicked
        // TODO add your handling code here:
        str = str.concat("    ");
        writeUser_.setText(str);
    }//GEN-LAST:event_tab_MouseClicked

    private void W_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("W");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("w");
        writeUser_.setText(str);
    }//GEN-LAST:event_W_MouseClicked

    private void E_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("E");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("e");
        writeUser_.setText(str);
    }//GEN-LAST:event_E_MouseClicked

    private void R_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("R");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("r");
        writeUser_.setText(str);
    }//GEN-LAST:event_R_MouseClicked

    private void T_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("T");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("t");
        writeUser_.setText(str);
    }//GEN-LAST:event_T_MouseClicked

    private void Y_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Y_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("Y");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("y");
        writeUser_.setText(str);
    }//GEN-LAST:event_Y_MouseClicked

    private void U_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("U");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("u");
        writeUser_.setText(str);
    }//GEN-LAST:event_U_MouseClicked

    private void I_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_I_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("I");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("i");
        writeUser_.setText(str);
    }//GEN-LAST:event_I_MouseClicked

    private void O_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("O");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("o");
        writeUser_.setText(str);
    }//GEN-LAST:event_O_MouseClicked

    private void P_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("P");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("p");
        writeUser_.setText(str);
    }//GEN-LAST:event_P_MouseClicked

    private void A_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("A");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("a");
        writeUser_.setText(str);
    }//GEN-LAST:event_A_MouseClicked

    private void S_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("S");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("s");
        writeUser_.setText(str);
    }//GEN-LAST:event_S_MouseClicked

    private void D_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("D");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("d");
        writeUser_.setText(str);
    }//GEN-LAST:event_D_MouseClicked

    private void F_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("F");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("f");
        writeUser_.setText(str);
    }//GEN-LAST:event_F_MouseClicked

    private void G_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("G");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("g");
        writeUser_.setText(str);
    }//GEN-LAST:event_G_MouseClicked

    private void H_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("H");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("h");
        writeUser_.setText(str);
    }//GEN-LAST:event_H_MouseClicked

    private void J_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("J");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("j");
        writeUser_.setText(str);
    }//GEN-LAST:event_J_MouseClicked

    private void K_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_K_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("K");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("k");
        writeUser_.setText(str);
    }//GEN-LAST:event_K_MouseClicked

    private void L_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("L");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("l");
        writeUser_.setText(str);
    }//GEN-LAST:event_L_MouseClicked

    private void Z_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Z_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("Z");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("z");
        writeUser_.setText(str);
    }//GEN-LAST:event_Z_MouseClicked

    private void X_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("X");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("x");
        writeUser_.setText(str);
    }//GEN-LAST:event_X_MouseClicked

    private void C_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("C");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("c");
        writeUser_.setText(str);
    }//GEN-LAST:event_C_MouseClicked

    private void V_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("V");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("v");
        writeUser_.setText(str);
    }//GEN-LAST:event_V_MouseClicked

    private void B_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("B");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("b");
        writeUser_.setText(str);
    }//GEN-LAST:event_B_MouseClicked

    private void N_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("N");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("n");
        writeUser_.setText(str);
    }//GEN-LAST:event_N_MouseClicked

    private void M_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MouseClicked
        // TODO add your handling code here:
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("M");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("m");
        writeUser_.setText(str);
    }//GEN-LAST:event_M_MouseClicked

    private void space_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_space_MouseClicked
        // TODO add your handling code here:
        str = str.concat(" ");
        writeUser_.setText(str);
    }//GEN-LAST:event_space_MouseClicked

    private void enter1_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1_MouseClicked
        // TODO add your handling code here:
        str = str.concat("\n");
        writeUser_.setText(str);
        
    }//GEN-LAST:event_enter1_MouseClicked
    
    
    String data = "";
    int subWordCount=0;
    int correctWordCount=0;
    int wrongWordCount=0;
    
    String []userArray = new String[20];
    
    private void submit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_MouseClicked
            //time ends
            elapsed = System.currentTimeMillis()-startTime;
            
            int i,j,k;
            String temp;
            // data word count and separate
               for(i=0,j=0,k=0; i< str.length();i++){
                   if(str.charAt(i)==' ' || str.charAt(i)=='\n' || str.charAt(i)=='\t'  || str.charAt(i)=='\0'){      
                        subWordCount++;
                        userArray[k]=str.substring(j, i);
                        j=i+1;
                        k++;
                   }
               }
               
               
               if(!str.isEmpty()){
               subWordCount++;
               userArray[k]=str.substring(j, str.length());
               }
               
               for(k=0;k<subWordCount;k++)
                   System.out.println(userArray[k]);
            System.out.println(subWordCount);
            
            
            
            
               
            if (data.equals(str)){
                System.out.println("match");
            }
            else System.out.println("not match");
            
            
            //match count
            for (int l=0;l<subWordCount;l++){
                if (userArray[l].equals(fileArray[l])){
                        correctWordCount++;
                }
                else wrongWordCount++;
            }
            
            
            System.out.println(correctWordCount);
            
            int nx = (int) getLocation().getX();
            int ny = (int) getLocation().getY();
            
            result rs = new result(nx-270, ny+150, fileWordCount,subWordCount,correctWordCount,elapsed);
            rs.setVisible(true);
    }//GEN-LAST:event_submit_MouseClicked
    
    
    //time
    long startTime;
    long endTime;
    long elapsed;

    
    int fileWordCount=0;
    String fileArray[]=new String[200];
    private void showText_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showText_MouseClicked
        try {
            // file write
            FileWriter fw = new FileWriter ("typeMaster.txt");
            fw.write("sample TEXT to show it works for");
            fw.close();
            
            // file read
            File f1 = new File("typeMaster.txt");
            Scanner sc = new Scanner(f1);
            while (sc.hasNextLine()){
                data = sc.nextLine();
            }
            data = data.concat("\na failure like me");
            
            // data word count and separate
               
               int i,j,k;
               for(i=0,j=0,k=0; i< data.length();i++){
                   if(data.charAt(i)==' ' || data.charAt(i)=='\n' || data.charAt(i)=='\t'  || data.charAt(i)=='\0'){      
                        fileWordCount++;
                        fileArray[k]=data.substring(j, i);
                        j=i+1;
                        k++;
                   }
               }
               
               
               if(!data.isEmpty()){
               fileWordCount++;
               fileArray[k]=data.substring(j, data.length());
               }
               
               for(k=0;k<fileWordCount;k++)
                   System.out.println(fileArray[k]);
            System.out.println(fileWordCount);
               
            // show text from file
            fileWrite_.setText(data);
            
            //time counting starts
            startTime = System.currentTimeMillis();
            
        } catch (IOException ex) {
            Logger.getLogger(typeMaster_mini.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showText_MouseClicked

    private void backspace_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspace_MouseClicked
        // TODO add your handling code here:
        if (str.isEmpty()==false)
        str = str.substring(0, str.length()-1);
        writeUser_.setText(str);
    }//GEN-LAST:event_backspace_MouseClicked

        int mouseX;
        int mouseY;
    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void Q_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q_MouseDragged

    }//GEN-LAST:event_Q_MouseDragged

    private void Q_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q_MouseMoved
        // TODO add your handling code here:
        ImageIcon qColor = new ImageIcon(getClass().getResource("/imageAll/q.png")); 
        Q_.setIcon(qColor); 
        
    }//GEN-LAST:event_Q_MouseMoved
    
    int x;
    int y;
    
    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        // TODO add your handling code here:
        
         x = evt.getXOnScreen();
         y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseMoved
        // TODO add your handling code here:
        A_.setIcon(null);   B_.setIcon(null);   C_.setIcon(null);   D_.setIcon(null);   E_.setIcon(null);   F_.setIcon(null);
        G_.setIcon(null);   H_.setIcon(null);   I_.setIcon(null);   J_.setIcon(null);   K_.setIcon(null);   L_.setIcon(null);   
        M_.setIcon(null);   N_.setIcon(null);   O_.setIcon(null);   P_.setIcon(null);   Q_.setIcon(null);   R_.setIcon(null);   
        S_.setIcon(null);   T_.setIcon(null);   U_.setIcon(null);   V_.setIcon(null);   W_.setIcon(null);   X_.setIcon(null);   
        Y_.setIcon(null);   Z_.setIcon(null);   
        one_.setIcon(null); two_.setIcon(null); three_.setIcon(null); four_.setIcon(null); five_.setIcon(null);
        six_.setIcon(null); seven_.setIcon(null); eight_.setIcon(null); nine_.setIcon(null); zero_.setIcon(null);
        symbl_.setIcon(null); equal_.setIcon(null); dash_.setIcon(null); brac1_.setIcon(null); brac2_.setIcon(null);
        semi_.setIcon(null); comma_.setIcon(null); slash_.setIcon(null); fullstop_.setIcon(null); backSlash_.setIcon(null); 
        udd_.setIcon(null); about_.setIcon(null); space_.setIcon(null); backspace_.setIcon(null); enterImage_.setIcon(null);
        submit_.setIcon(null); tab_.setIcon(null);
        if(capsLockFlag==false){
            capsLock_.setIcon(null);
        }
        if (shiftFlag == 0){
        rightShift_.setIcon(null);
        leftShift_.setIcon(null);
        }
        
    }//GEN-LAST:event_dragMouseMoved

    private void W_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W_MouseMoved
        ImageIcon wColor = new ImageIcon(getClass().getResource("/imageAll/w.png")); 
        W_.setIcon(wColor);
    }//GEN-LAST:event_W_MouseMoved

    private void E_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E_MouseMoved
        ImageIcon eColor = new ImageIcon(getClass().getResource("/imageAll/e.png")); 
        E_.setIcon(eColor);
    }//GEN-LAST:event_E_MouseMoved

    private void R_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_MouseMoved
        ImageIcon rColor = new ImageIcon(getClass().getResource("/imageAll/r.png")); 
        R_.setIcon(rColor);
    }//GEN-LAST:event_R_MouseMoved

    private void T_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_MouseMoved
        ImageIcon tColor = new ImageIcon(getClass().getResource("/imageAll/t.png")); 
        T_.setIcon(tColor);
    }//GEN-LAST:event_T_MouseMoved

    private void Y_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Y_MouseMoved
        ImageIcon yColor = new ImageIcon(getClass().getResource("/imageAll/y.png")); 
        Y_.setIcon(yColor);
    }//GEN-LAST:event_Y_MouseMoved

    private void U_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_MouseMoved
        ImageIcon uColor = new ImageIcon(getClass().getResource("/imageAll/u.png")); 
        U_.setIcon(uColor);
    }//GEN-LAST:event_U_MouseMoved

    private void I_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_I_MouseMoved
        ImageIcon iColor = new ImageIcon(getClass().getResource("/imageAll/i.png")); 
        I_.setIcon(iColor);
    }//GEN-LAST:event_I_MouseMoved

    private void O_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O_MouseMoved
        ImageIcon oColor = new ImageIcon(getClass().getResource("/imageAll/o.png")); 
        O_.setIcon(oColor);
    }//GEN-LAST:event_O_MouseMoved

    private void P_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_MouseMoved
        ImageIcon pColor = new ImageIcon(getClass().getResource("/imageAll/p.png")); 
        P_.setIcon(pColor);
    }//GEN-LAST:event_P_MouseMoved

    private void A_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_MouseMoved
        ImageIcon aColor = new ImageIcon(getClass().getResource("/imageAll/a.png")); 
        A_.setIcon(aColor);
    }//GEN-LAST:event_A_MouseMoved

    private void S_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MouseMoved
        ImageIcon sColor = new ImageIcon(getClass().getResource("/imageAll/s.png")); 
        S_.setIcon(sColor);
    }//GEN-LAST:event_S_MouseMoved

    private void D_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_MouseMoved
        ImageIcon dColor = new ImageIcon(getClass().getResource("/imageAll/d.png")); 
        D_.setIcon(dColor);
    }//GEN-LAST:event_D_MouseMoved

    private void F_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F_MouseMoved
        ImageIcon fColor = new ImageIcon(getClass().getResource("/imageAll/f.png")); 
        F_.setIcon(fColor);
    }//GEN-LAST:event_F_MouseMoved

    private void G_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G_MouseMoved
        ImageIcon gColor = new ImageIcon(getClass().getResource("/imageAll/g.png")); 
        G_.setIcon(gColor);
    }//GEN-LAST:event_G_MouseMoved

    private void H_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H_MouseMoved
        ImageIcon hColor = new ImageIcon(getClass().getResource("/imageAll/h.png")); 
        H_.setIcon(hColor);
    }//GEN-LAST:event_H_MouseMoved

    private void J_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_MouseMoved
        ImageIcon jColor = new ImageIcon(getClass().getResource("/imageAll/j.png")); 
        J_.setIcon(jColor);
    }//GEN-LAST:event_J_MouseMoved

    private void K_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_K_MouseMoved
        ImageIcon kColor = new ImageIcon(getClass().getResource("/imageAll/k.png")); 
        K_.setIcon(kColor);
    }//GEN-LAST:event_K_MouseMoved

    private void L_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_MouseMoved
        ImageIcon lColor = new ImageIcon(getClass().getResource("/imageAll/l.png")); 
        L_.setIcon(lColor);
    }//GEN-LAST:event_L_MouseMoved

    private void Z_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Z_MouseMoved
        ImageIcon zColor = new ImageIcon(getClass().getResource("/imageAll/z.png")); 
        Z_.setIcon(zColor);
    }//GEN-LAST:event_Z_MouseMoved

    private void X_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_MouseMoved
        ImageIcon xColor = new ImageIcon(getClass().getResource("/imageAll/x.png")); 
        X_.setIcon(xColor);
    }//GEN-LAST:event_X_MouseMoved

    private void C_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_MouseMoved
        ImageIcon cColor = new ImageIcon(getClass().getResource("/imageAll/c.png")); 
        C_.setIcon(cColor);
    }//GEN-LAST:event_C_MouseMoved

    private void V_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V_MouseMoved
        ImageIcon vColor = new ImageIcon(getClass().getResource("/imageAll/v.png")); 
        V_.setIcon(vColor);
    }//GEN-LAST:event_V_MouseMoved

    private void B_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_MouseMoved
        ImageIcon bColor = new ImageIcon(getClass().getResource("/imageAll/b.png")); 
        B_.setIcon(bColor);
    }//GEN-LAST:event_B_MouseMoved

    private void N_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_MouseMoved
        ImageIcon nColor = new ImageIcon(getClass().getResource("/imageAll/n.png")); 
        N_.setIcon(nColor);
    }//GEN-LAST:event_N_MouseMoved

    private void M_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MouseMoved
        ImageIcon mColor = new ImageIcon(getClass().getResource("/imageAll/m.png")); 
        M_.setIcon(mColor);
    }//GEN-LAST:event_M_MouseMoved

    private void space_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_space_MouseMoved
        ImageIcon spaceColor = new ImageIcon(getClass().getResource("/imageAll/space.png")); 
        space_.setIcon(spaceColor);
    }//GEN-LAST:event_space_MouseMoved

    private void symbl_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symbl_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("~");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("`");
        writeUser_.setText(str);
    }//GEN-LAST:event_symbl_MouseClicked

    private void one_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("!");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("1");
        writeUser_.setText(str);
        
    }//GEN-LAST:event_one_MouseClicked

    private void two_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("@");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("2");
        writeUser_.setText(str);
    }//GEN-LAST:event_two_MouseClicked

    private void three_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_three_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("#");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("3");
        writeUser_.setText(str);
    }//GEN-LAST:event_three_MouseClicked

    private void four_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_four_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("$");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
        }
        else str = str.concat("4");
        writeUser_.setText(str);
    }//GEN-LAST:event_four_MouseClicked

    private void five_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_five_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("%");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("5");
        writeUser_.setText(str);
    }//GEN-LAST:event_five_MouseClicked

    private void six_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_six_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("^");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("6");
        writeUser_.setText(str);
    }//GEN-LAST:event_six_MouseClicked

    private void seven_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seven_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("&");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("7");
        writeUser_.setText(str);
    }//GEN-LAST:event_seven_MouseClicked

    private void brac1_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brac1_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("{");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("[");
        writeUser_.setText(str);
    }//GEN-LAST:event_brac1_MouseClicked

    private void brac2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brac2_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("}");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("]");
        writeUser_.setText(str);
    }//GEN-LAST:event_brac2_MouseClicked

    private void semi_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semi_MouseClicked
        if (shiftFlag == 1){
            str = str.concat(":");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat(";");
        writeUser_.setText(str);
    }//GEN-LAST:event_semi_MouseClicked

    private void udd_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udd_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("\"");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("'");
        writeUser_.setText(str);
    }//GEN-LAST:event_udd_MouseClicked

    private void comma_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comma_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("<");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat(",");
        writeUser_.setText(str);
    }//GEN-LAST:event_comma_MouseClicked

    private void fullstop_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullstop_MouseClicked
        if (shiftFlag == 1){
            str = str.concat(">");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat(".");
        writeUser_.setText(str);
    }//GEN-LAST:event_fullstop_MouseClicked

    private void slash_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slash_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("?");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("/");
        writeUser_.setText(str);
    }//GEN-LAST:event_slash_MouseClicked

    private void rightShift_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightShift_MouseClicked
        shiftFlag  = 1;
       // ImageIcon oneColor = new ImageIcon(getClass().getResource("/imageAll/1.png")); 
       // rightShift_.setIcon(oneColor);
    }//GEN-LAST:event_rightShift_MouseClicked

    private void backSlash_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backSlash_MouseClicked
        if (shiftFlag == 1){
            str = str.concat("|");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("\\");
        writeUser_.setText(str);
    }//GEN-LAST:event_backSlash_MouseClicked

    private void symbl_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symbl_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/`.png")); 
        symbl_.setIcon(symColor);
    }//GEN-LAST:event_symbl_MouseMoved

    private void one_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_MouseMoved
        ImageIcon oneColor = new ImageIcon(getClass().getResource("/imageAll/1.png")); 
        one_.setIcon(oneColor);
    }//GEN-LAST:event_one_MouseMoved

    private void two_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/2.png")); 
        two_.setIcon(symColor);
    }//GEN-LAST:event_two_MouseMoved

    private void three_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_three_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/3.png")); 
        three_.setIcon(symColor);
    }//GEN-LAST:event_three_MouseMoved

    private void four_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_four_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/4.png")); 
        four_.setIcon(symColor);
    }//GEN-LAST:event_four_MouseMoved

    private void five_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_five_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/5.png")); 
        five_.setIcon(symColor);
    }//GEN-LAST:event_five_MouseMoved

    private void six_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_six_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/6.png")); 
        six_.setIcon(symColor);
    }//GEN-LAST:event_six_MouseMoved

    private void seven_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seven_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/7.png")); 
        seven_.setIcon(symColor);
    }//GEN-LAST:event_seven_MouseMoved

    private void eight_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eight_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/8.png")); 
        eight_.setIcon(symColor);
    }//GEN-LAST:event_eight_MouseMoved

    private void nine_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nine_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/9.png")); 
        nine_.setIcon(symColor);
    }//GEN-LAST:event_nine_MouseMoved

    private void zero_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zero_MouseClicked
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat(")");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("0");
        writeUser_.setText(str);
    }//GEN-LAST:event_zero_MouseClicked

    private void zero_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zero_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/0.png")); 
        zero_.setIcon(symColor);
    }//GEN-LAST:event_zero_MouseMoved

    private void dash_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash_MouseClicked
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("_");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("-");
        writeUser_.setText(str);
    }//GEN-LAST:event_dash_MouseClicked

    private void dash_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/-.png")); 
        dash_.setIcon(symColor);
    }//GEN-LAST:event_dash_MouseMoved

    private void equal_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equal_MouseClicked
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("+");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("=");
        writeUser_.setText(str);
    }//GEN-LAST:event_equal_MouseClicked

    private void equal_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equal_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/=.png")); 
        equal_.setIcon(symColor);
    }//GEN-LAST:event_equal_MouseMoved

    private void backspace_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspace_MouseMoved
        ImageIcon enColor = new ImageIcon(getClass().getResource("/imageAll/backspace.png")); 
        backspace_.setIcon(enColor);
    }//GEN-LAST:event_backspace_MouseMoved

    private void brac1_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brac1_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/[.png")); 
        brac1_.setIcon(symColor);
    }//GEN-LAST:event_brac1_MouseMoved

    private void brac2_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brac2_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/].png")); 
        brac2_.setIcon(symColor);
    }//GEN-LAST:event_brac2_MouseMoved

    private void semi_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semi_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/;.png")); 
        semi_.setIcon(symColor);
    }//GEN-LAST:event_semi_MouseMoved

    private void udd_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udd_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/'.png")); 
        udd_.setIcon(symColor);
    }//GEN-LAST:event_udd_MouseMoved

    private void comma_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comma_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/,.png")); 
        comma_.setIcon(symColor);
    }//GEN-LAST:event_comma_MouseMoved

    private void fullstop_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullstop_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/..png")); 
        fullstop_.setIcon(symColor);
    }//GEN-LAST:event_fullstop_MouseMoved

    private void slash_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slash_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/slash.png")); 
        slash_.setIcon(symColor);
    }//GEN-LAST:event_slash_MouseMoved

    private void backSlash_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backSlash_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/slashBack.png")); 
        backSlash_.setIcon(symColor);
    }//GEN-LAST:event_backSlash_MouseMoved

    private void rightShift_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightShift_MouseMoved
        ImageIcon shiftColor = new ImageIcon(getClass().getResource("/imageAll/rightShift.png")); 
        rightShift_.setIcon(shiftColor);
    }//GEN-LAST:event_rightShift_MouseMoved

    private void submit_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_MouseMoved
        ImageIcon subColor = new ImageIcon(getClass().getResource("/imageAll/submit.png")); 
        submit_.setIcon(subColor);
    }//GEN-LAST:event_submit_MouseMoved

    private void about_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_MouseMoved
        ImageIcon symColor = new ImageIcon(getClass().getResource("/imageAll/mystic.png")); 
        about_.setIcon(symColor);
    }//GEN-LAST:event_about_MouseMoved

    private void eight_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eight_MouseClicked
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("*");  
            shiftFlag = 0;
            leftShift_.setIcon(null);
            rightShift_.setIcon(null);
        }
        else str = str.concat("8");
        writeUser_.setText(str);
    }//GEN-LAST:event_eight_MouseClicked

    private void nine_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nine_MouseClicked
        if (shiftFlag == 1 || capsLockFlag == true){
            str = str.concat("(");  
            shiftFlag = 0;
            //leftShift_.setIcon(icon);
        }
        else str = str.concat("9");
        writeUser_.setText(str);
    }//GEN-LAST:event_nine_MouseClicked

    private void tab_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_MouseMoved
        ImageIcon tabColor = new ImageIcon(getClass().getResource("/imageAll/tab.png")); 
        tab_.setIcon(tabColor);
    }//GEN-LAST:event_tab_MouseMoved

    private void capsLock_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capsLock_MouseMoved
        ImageIcon capsColor = new ImageIcon(getClass().getResource("/imageAll/caps.png")); 
        capsLock_.setIcon(capsColor);
    }//GEN-LAST:event_capsLock_MouseMoved

    private void leftShift_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftShift_MouseMoved
        ImageIcon shiftColor = new ImageIcon(getClass().getResource("/imageAll/leftShift.png"));
        leftShift_.setIcon(shiftColor);
    }//GEN-LAST:event_leftShift_MouseMoved

    private void enterImage_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterImage_MouseMoved

    }//GEN-LAST:event_enterImage_MouseMoved

    private void enter1_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1_MouseMoved
        ImageIcon shiftColor = new ImageIcon(getClass().getResource("/imageAll/enter.png"));
        enterImage_.setIcon(shiftColor);
    }//GEN-LAST:event_enter1_MouseMoved

    private void enter2_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2_MouseMoved
        ImageIcon shiftColor = new ImageIcon(getClass().getResource("/imageAll/enter.png"));
        enterImage_.setIcon(shiftColor);
    }//GEN-LAST:event_enter2_MouseMoved

    private void about_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_MouseClicked
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        about abt = new about (nx+810,ny+150);
        abt.setVisible(true);
    }//GEN-LAST:event_about_MouseClicked

    private void enter2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2_MouseClicked
        str = str.concat("\n");
        writeUser_.setText(str);
    }//GEN-LAST:event_enter2_MouseClicked

    private void drgen_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drgen_MouseMoved
        enterImage_.setIcon(null);
        brac2_.setIcon(null);
    }//GEN-LAST:event_drgen_MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(typeMaster_mini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(typeMaster_mini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(typeMaster_mini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(typeMaster_mini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new typeMaster_mini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_;
    private javax.swing.JLabel B_;
    private javax.swing.JLabel C_;
    private javax.swing.JLabel D_;
    private javax.swing.JLabel E_;
    private javax.swing.JLabel F_;
    private javax.swing.JLabel G_;
    private javax.swing.JLabel H_;
    private javax.swing.JLabel I_;
    private javax.swing.JLabel J_;
    private javax.swing.JLabel K_;
    private javax.swing.JLabel L_;
    private javax.swing.JLabel M_;
    private javax.swing.JLabel N_;
    private javax.swing.JLabel O_;
    private javax.swing.JLabel P_;
    private javax.swing.JLabel Q_;
    private javax.swing.JLabel R_;
    private javax.swing.JLabel S_;
    private javax.swing.JLabel T_;
    private javax.swing.JLabel U_;
    private javax.swing.JLabel V_;
    private javax.swing.JLabel W_;
    private javax.swing.JLabel X_;
    private javax.swing.JLabel Y_;
    private javax.swing.JLabel Z_;
    private javax.swing.JLabel about_;
    private javax.swing.JLabel backSlash_;
    private javax.swing.JLabel backspace_;
    private javax.swing.JLabel brac1_;
    private javax.swing.JLabel brac2_;
    private javax.swing.JLabel capsLock_;
    private javax.swing.JLabel comma_;
    private javax.swing.JLabel dash_;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel drgen_;
    private javax.swing.JLabel eight_;
    private javax.swing.JLabel enter1_;
    private javax.swing.JLabel enter2_;
    private javax.swing.JLabel enterImage_;
    private javax.swing.JLabel equal_;
    private javax.swing.JLabel exit_;
    private javax.swing.JTextArea fileWrite_;
    private javax.swing.JLabel five_;
    private javax.swing.JLabel four_;
    private javax.swing.JLabel fullstop_;
    private javax.swing.JLabel leftShift_;
    private javax.swing.JLabel nine_;
    private javax.swing.JLabel one_;
    private javax.swing.JScrollPane pathetic2_;
    private javax.swing.JScrollPane pathetic_;
    private javax.swing.JLabel rightShift_;
    private javax.swing.JLabel semi_;
    private javax.swing.JLabel seven_;
    private javax.swing.JLabel showText_;
    private javax.swing.JLabel six_;
    private javax.swing.JLabel slash_;
    private javax.swing.JLabel space_;
    private javax.swing.JLabel submit_;
    private javax.swing.JLabel symbl_;
    private javax.swing.JLabel tab_;
    private javax.swing.JLabel three_;
    private javax.swing.JLabel two_;
    private javax.swing.JLabel udd_;
    private javax.swing.JTextArea writeUser_;
    private javax.swing.JLabel zero_;
    // End of variables declaration//GEN-END:variables
}
